name: CI-CD Pipeline

on:
  push:
    branches:
      - master

env:
  APP_PORT: 3000
  IMAGE_NAME: gabr1
  CONTAINER_NAME: gabr1_app

jobs:
  build-test-package-deploy:
    runs-on: ubuntu-latest

    steps:

    # 1️⃣ Checkout
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2️⃣ Setup Node
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm ci

    # 3️⃣ Clean
    - name: Clean Old Build
      run: rm -rf dist || true

    # 4️⃣ Build
    - name: Build Application
      run: npm run build

    # 5️⃣ Test
    - name: Run Tests
      run: npm test

    # 6️⃣ Package - Build Docker Image
    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:${{ github.sha }} .

    - name: tag to dockerhub
      run: docker tag $IMAGE_NAME:${{ github.sha }} rahamshaik/gabrimage

     - name: Dockerlogin
      run: docker login -u ${{ docker_user }} -p ${{ docker_password }}

    - name: push to dockerhub
      run: docker push rahamshaik/gabtimage

    
    # 8️⃣ Email Notification
    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_HOST }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.SMTP_USER }}
        password: ${{ secrets.SMTP_PASS }}
        subject: "GitHub Actions Pipeline Status"
        to: ${{ secrets.NOTIFY_EMAIL }}
        from: ${{ secrets.SMTP_USER }}
        body: |
          Pipeline Status: ${{ job.status }}
          Repository: ${{ github.repository }}
          Commit: ${{ github.sha }}
          Branch: ${{ github.ref_name }}

 
